Fix notify silently fails
projectdiscovery/notify pull request #146
Opened 2022-06-10 05:00 UTC by parrasajad

* set buffer to file size
* split line into multiple chunks if line size is greater than char-limit

2022-06-10 06:34 UTC, Mzack9999 requested changes

2022-06-10 06:34 UTC, Mzack9999 commented on internal/runner/util.go
> +func SlitInChunks(data string, charLimit int) []string {
`SlitInChunks` => `SplitInChunks`

2022-06-10 08:08 UTC, Mzack9999 approved these changes

2022-06-10 16:10 UTC, ehsandeep approved these changes

2022-06-10 16:10 UTC, merged

2022-06-10 23:09 UTC, justinsteven commented
@ehsandeep I'm having problems with this, I think it needs to be backed out.

Before this PR was landed:

```
% git log -n1
commit b947254064e6c09d18b56e1064cbcbabb0e21e72 (HEAD)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Fri Jun 10 00:51:23 2022 +0530

    chore(deps): bump golang from 1.18.2-alpine to 1.18.3-alpine (#144)

    Bumps golang from 1.18.2-alpine to 1.18.3-alpine.

    ---
    updated-dependencies:
    - dependency-name: golang
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

% go build .

% id | ./notify

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml
uid=31337(justin) gid=31337(justin) groups=31337(justin),27(sudo)

% id | ./notify -bulk

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml
uid=31337(justin) gid=31337(justin) groups=31337(justin),27(sudo)

% ./notify -i /etc/issue

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml
Debian GNU/Linux 10 \n \l

% ./notify -i /etc/issue -bulk

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml
Debian GNU/Linux 10 \n \l
```

File-based and stdin with bulk and non-bulk all work.

As of this PR being landed:

```
% id | ./notify

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml

% id | ./notify -bulk

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml

% ./notify -i /etc/issue

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml
Debian GNU/Linux 10 \n \l

% ./notify -i /etc/issue -bulk

             __  _ ___
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / v1.0.2-dev
                   /___/

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
Using default provider config: /home/justin/.config/notify/provider-config.yaml
```

stdin is broken, and file-based bulk is broken

I can see that this PR is getting the size of the infile. I suspect this breaks for stdin, and for file-based it could cause memory pressure given a large infile.

I think we need to write a new `bufio.SplitFunc` similarly to that in #130, or tweak the one in #130 to also be usable in non-bulk mode (i.e. to split on newlines)

2022-06-11 19:00 UTC, ehsandeep commented
@justinsteven thanks for pointing it out, it should be addressed in https://github.com/projectdiscovery/notify/pull/149