SelectFormat fix
projectdiscovery/notify pull request #162
Opened 2022-08-08 10:54 UTC by parrasajad

2022-08-09 09:03 UTC, Mzack9999 requested changes

2022-08-09 09:03 UTC, Mzack9999 commented on pkg/utils/utils.go
> +	fmt.Println("cliFormat: ", cliFormat)
Please remove debug instructions

2022-08-10 06:47 UTC, Mzack9999 approved these changes

2022-08-10 16:19 UTC, ehsandeep approved these changes

2022-08-10 16:20 UTC, merged