Set provider config from ENV vars instead of plain text files
projectdiscovery/notify pull request #249
Opened 2023-04-27 11:09 UTC by iamargus95

- [x] Walkfunc implemented
- [ ] Set all types of config values
       - [x] String
       - [ ] Bool
       - [ ] []string
       - [ ] map[string]string

2023-05-03 06:41 UTC, ShubhamRasal commented
we can go with second approach..
```go
// utils.go
func readProviderConfig(filepath string) (io.Reader, error) {
	// Open the file
	file, err := os.Open(filepath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	// Create a scanner to read the file line by line
	scanner := bufio.NewScanner(file)

	// Create a string builder to accumulate the modified data
	var sb strings.Builder

	// Iterate over each line and do variable substitution
	for scanner.Scan() {
		line := scanner.Text()
		newLine := substituteEnvVars(line)
		sb.WriteString(newLine)
		sb.WriteString("\n")
	}
	// Check for errors
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return strings.NewReader(sb.String()), nil
}

func substituteEnvVars(line string) string {
	for _, word := range strings.Fields(line) {
		word = strings.Trim(word, " \"")
		if strings.HasPrefix(word, "$") {
			key := strings.TrimPrefix(word, "$")
			val := os.Getenv(key)
			line = strings.ReplaceAll(line, word, val)
		}
	}
	return line
}
```
`runner.go`
```go
	reader, err := readProviderConfig(options.ProviderConfig)
	if err != nil {
		return nil, errors.Wrap(err, "could not open provider config file")
	}
	if parseErr := yaml.NewDecoder(reader).Decode(&providerOptions); parseErr != nil {
		return nil, errors.Wrap(parseErr, "could not parse provider config file")
	}
```

2023-05-09 07:44 UTC, tarunKoyalwar requested changes
nice work @iamargus95 , lgtm ! verified locally and seems to work 
ex config
```console
cat ~/.config/notify/provider-config.yaml
discord:
  - id: "crawl"
    discord_channel: "crawl"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: "$DISCORD_WEBHOOK_URL"

```

2023-05-09 07:45 UTC, tarunKoyalwar commented
@iamargus95 , since this is a generic implementation what do you think of creating new PR to move this function to https://github.com/projectdiscovery/utils/tree/main/file . that way we can extend this support to other projects

Thanks

2023-05-09 07:55 UTC, iamargus95 commented on internal/runner/runner.go
> +		word = strings.Trim(word, " \"")
Done ✅ 😇

2023-05-09 08:48 UTC, iamargus95 commented
@tarunKoyalwar 
Kindly review this PR in utils.
I've added this functionality as a helper.
- https://github.com/projectdiscovery/utils/pull/149

2023-05-15 10:52 UTC, tarunKoyalwar requested changes
@iamargus95 , since upstream pr https://github.com/projectdiscovery/utils/pull/149 is merged now can you update this PR to use those helper utils

2023-05-16 04:59 UTC, iamargus95 commented
> @iamargus95 , since upstream pr [projectdiscovery/utils#149](https://github.com/projectdiscovery/utils/pull/149) is merged now can you update this PR to use those helper utils

@tarunKoyalwar I think the latest release (v0.0.30) does not have the newly added helper function. Waiting for it to be added.

2023-05-16 10:11 UTC, ehsandeep commented
> > @iamargus95 , since upstream pr [projectdiscovery/utils#149](https://github.com/projectdiscovery/utils/pull/149) is merged now can you update this PR to use those helper utils
> 
> @tarunKoyalwar I think the latest release (v0.0.30) does not have the newly added helper function. Waiting for it to be added.

https://github.com/projectdiscovery/utils/releases/tag/v0.0.31

2023-05-27 15:31 UTC, merged