fix proxy setting when ratelimit is 0
projectdiscovery/notify pull request #402
Opened 2024-07-31 13:27 UTC by AaronChen0

When ratelimit is set to 0, or not set both in command line and `config.yaml`, the proxy config is ignored since `defaultTransport` is not used.

In addition, [net.http.Transport](https://pkg.go.dev/net/http#Transport) supports both http and socks5 proxy, so I add info to `README`.

2024-08-01 09:56 UTC, GeorginaReeder commented
Thanks for your contribution @AaronChen0 !

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

2024-08-01 17:00 UTC, dwisiswant0 commented
Could you please create the issue first, @AaronChen0?

2024-08-02 02:05 UTC, dwisiswant0 requested changes

2024-08-02 02:05 UTC, dwisiswant0 commented on internal/runner/runner.go
> +		http.DefaultClient.Transport = defaultTransport
I think we should avoid unnecessary nesting to make things clearer and potential for slightly better perf.

```go
	http.DefaultClient.Transport = defaultTransport
	if r.options.RateLimit > 0 {
		http.DefaultClient.Transport = utils.NewThrottledTransport(time.Second, r.options.RateLimit, defaultTransport)
	}
```

2024-08-02 03:20 UTC, AaronChen0 commented
Changes made. @dwisiswant0

2024-08-02 09:35 UTC, dwisiswant0 approved these changes
LGTM.

2024-08-02 10:20 UTC, ehsandeep approved these changes

2024-08-05 13:33 UTC, AaronChen0 commented
The failed check is irrelevant to this pull request.

Switching branch from `main` to `dev` introduced a commit not by me. Is this a concern when later `dev` branch merges back to `main` branch?

2024-08-05 18:04 UTC, dwisiswant0 commented
@AaronChen0 - you should rebase your branch.

2024-08-06 01:19 UTC, AaronChen0 commented
@dwisiswant0.  Rebase done.

2024-08-06 08:30 UTC, dwisiswant0 approved these changes

2024-08-08 18:55 UTC, merged