add stdin-all flag
projectdiscovery/notify pull request #55
Opened 2021-07-05 15:00 UTC by parrasajad

- Add `stdin-all` flag
- For now it errors out when the content length limit is crossed (different for different platforms)

2021-07-16 20:52 UTC, Mzack9999 requested changes

2021-07-16 20:52 UTC, Mzack9999 commented on internal/runner/runner.go
> +			if err != nil {
What if we merge the two if from:

```
if err != nil {
    gologger.Fatal().Msgf("%s\n", err)
}
if n == 0 {
    gologger.Fatal().Msgf("%s\n", err)
}
```
To:
```
if err != nil || n == 0 {
    gologger.Fatal().Msgf("%s\n", err)
}
```

2021-07-23 12:47 UTC, Mzack9999 approved these changes

2021-07-23 23:44 UTC, ehsandeep commented
Unable to test as I'm getting the following error with current goflags, and another issue with the latest one.

```
go: github.com/projectdiscovery/goflags@v0.0.5-0.20210625074658-a323e95c0c3b: invalid version: unknown revision a323e95c0c3b
```

with latest goflags:-

```
# command-line-arguments
./notify.go:49:9: undefined: goflags.New
```

@parrasajad Can we replace `stdin-all` with `bulk` flag.

2021-07-24 15:48 UTC, ehsandeep approved these changes
Working as expected with file input but not with stdin that we can handle is a separate issue/PR

```
subfinder -d hackerone.com | ./notify -bulk

             __  _ ___    
  ___  ___  / /_(_) _/_ __
 / _ \/ _ \/ __/ / _/ // /
/_//_/\___/\__/_/_/ \_, / 0.0.2 
                   /___/  

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[FTL] %!s(<nil>)
```

2021-07-24 15:49 UTC, merged